// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kslhjqmemgirsjplkmft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbGhqcW1lbWdpcnNqcGxrbWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTQ5NzQsImV4cCI6MjA2Nzg3MDk3NH0.vjEfCfKP6Kx96j_T0Ye_X03lr3f16eqD2lTfZsTaSjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});